version: '3'

services: 
  demo-web:
    image: demo-app
    deploy: 
      replicas: 2
      resources:
        limits: 
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: on-failure
    ports: 
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - webnet
      
networks:
  webnet: