version: 2.1

jobs:
  build:
    docker: 
      - image: circleci/node:10 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run: npm install
      - run: npm run build
      - run: echo $IMAGE_NAME
      - run: docker build -t $IMAGE_NAME -f prod.Dockerfile .
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run: echo $IMAGE_NAME
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master